name: halo_safety_dashboard
description: A parental control and child safety dashboard app
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  webview_flutter: ^4.8.0
  http: ^1.2.2
  flutter_secure_storage: ^9.2.2
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_messaging: ^16.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Uncomment if you add images, fonts, etc.
  # assets:
  #   - assets/images/
  #   - assets/fonts/
